//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despachos
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo_de_accion { get; set; }
        public string Cliente { get; set; }
        public string contacto { get; set; }
        public string Detalle_de_productos { get; set; }
    }
}
