//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despachos
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo_de_accion { get; set; }
        public string Cliente { get; set; }
        public string contacto { get; set; }
        public string Detalle_de_productos { get; set; }
    }
}
